version: '3'
services:
  positioning-fe-server:
    build:
      context: ./FE/react/positioning-tool
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    command: npm start
  positioning-python-server:
    build: 
      context: ./BE/PYTHON/HTTP/HTTPServer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws:/root/.aws
      - ~/Downloads/positioning-data:/data
    command: /opt/conda/bin/python /home/server.py
  positioning-cpp-server:
    build:
      context: ./BE/CPP/HTTP/RTK/rtk_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ~/Downloads/positioning-data:/data
    command: /home/rtk_service
  positioning-go-server:
    build:
      context: ./BE/GOLANG/HTTP/SERVER/positioning_db_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ~/Downloads/positioning-data:/data
    command: /home/db_service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: grab_datastore
      MYSQL_USER: writer
      MYSQL_PASSWORD: 123456
    volumes:
      - /Users/xiaolong.ji/dbdata:/var/lib/mysql
      - ./BE/GOLANG/HTTP/SERVER/Airport/cmd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        aliases:
          - db
    expose:
      - 3306
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 5
  airport:
    build:
      context: ./BE/GOLANG/HTTP/SERVER/Airport
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ~/Downloads/airport:/data
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: writer
      DB_PASSWORD: 123456
      DB_NAME: grab_datastore
    ports:
      - "8006:8006"
    networks:
      default:
        aliases:
          - db

networks:
  default:
    driver: bridge